import type { Bucket, CollectionCard, FileItem } from "@/lib/models/archive";
import type { TransferItem } from "@/lib/models/transfers";
import { buildArchiveHref } from "@/lib/utils/archive-path";

export const buckets: Bucket[] = [
  {
    id: "my-archive",
    name: "My Archive",
    kind: "archive",
    description: "Private collections, media, and long-term storage.",
  },
  {
    id: "shared",
    name: "Shared",
    kind: "shared",
    description: "Spaces and shared collections from collaborators.",
  },
  {
    id: "vault",
    name: "Vault",
    kind: "vault",
    description: "Sensitive documents stored in a quieter, protected area.",
  },
];

export const files: FileItem[] = [
  {
    id: "folder-projects",
    bucketId: "my-archive",
    kind: "folder",
    fileType: "folder",
    name: "Projects",
    slug: "Projects",
    path: [],
    owner: "Me",
    updatedAt: "2026-04-18T17:20:00.000Z",
    tags: ["Work", "Planning"],
  },
  {
    id: "folder-work-assets",
    bucketId: "my-archive",
    kind: "folder",
    fileType: "folder",
    name: "Work Assets",
    slug: "Work Assets",
    path: [],
    owner: "Me",
    updatedAt: "2026-04-18T15:20:00.000Z",
    tags: ["Work"],
  },
  {
    id: "folder-travel-photos",
    bucketId: "my-archive",
    kind: "folder",
    fileType: "folder",
    name: "Travel Photos",
    slug: "Travel Photos",
    path: [],
    owner: "Me",
    updatedAt: "2026-04-17T17:20:00.000Z",
    shared: true,
    tags: ["Photography", "Personal"],
  },
  {
    id: "folder-financials",
    bucketId: "my-archive",
    kind: "folder",
    fileType: "folder",
    name: "Financials 2024",
    slug: "Financials 2024",
    path: [],
    owner: "Me",
    updatedAt: "2026-04-11T17:20:00.000Z",
    vaulted: true,
    tags: ["Private"],
  },
  {
    id: "folder-2024-rebrand",
    bucketId: "my-archive",
    kind: "folder",
    fileType: "folder",
    name: "2024 Rebrand",
    slug: "2024 Rebrand",
    path: ["Projects"],
    owner: "Me",
    updatedAt: "2026-04-18T17:20:00.000Z",
    tags: ["Brand", "Client"],
  },
  {
    id: "file-brand-guidelines",
    bucketId: "my-archive",
    kind: "file",
    fileType: "pdf",
    name: "brand_guidelines.pdf",
    slug: "brand_guidelines.pdf",
    path: ["Projects", "2024 Rebrand"],
    owner: "Me",
    updatedAt: "2026-04-18T16:45:00.000Z",
    sizeBytes: 12400000,
    tags: ["Brand", "Reference"],
    starred: true,
  },
  {
    id: "file-hero-image",
    bucketId: "my-archive",
    kind: "file",
    fileType: "image",
    name: "hero_image.png",
    slug: "hero_image.png",
    path: ["Projects", "2024 Rebrand"],
    owner: "Me",
    updatedAt: "2026-04-17T16:10:00.000Z",
    sizeBytes: 4200000,
    tags: ["Image", "Brand"],
  },
  {
    id: "file-timeline",
    bucketId: "my-archive",
    kind: "file",
    fileType: "csv",
    name: "timeline.csv",
    slug: "timeline.csv",
    path: ["Projects", "2024 Rebrand"],
    owner: "Me",
    updatedAt: "2026-04-15T14:00:00.000Z",
    sizeBytes: 845000,
    tags: ["Spreadsheet"],
  },
  {
    id: "folder-archive-2023",
    bucketId: "my-archive",
    kind: "folder",
    fileType: "folder",
    name: "Archive_2023",
    slug: "Archive_2023",
    path: ["Projects", "2024 Rebrand"],
    owner: "Me",
    updatedAt: "2026-04-01T10:15:00.000Z",
    tags: ["Archive"],
  },
  {
    id: "file-q3-strategy",
    bucketId: "my-archive",
    kind: "file",
    fileType: "pdf",
    name: "Q3_Marketing_Strategy.pdf",
    slug: "Q3_Marketing_Strategy.pdf",
    path: [],
    owner: "Me",
    updatedAt: "2026-04-18T18:05:00.000Z",
    sizeBytes: 16800000,
    tags: ["Strategy", "Reference"],
    starred: true,
  },
  {
    id: "file-hero-image-final",
    bucketId: "my-archive",
    kind: "file",
    fileType: "image",
    name: "Hero_Image_Final.jpg",
    slug: "Hero_Image_Final.jpg",
    path: [],
    owner: "Me",
    updatedAt: "2026-04-18T14:05:00.000Z",
    sizeBytes: 9200000,
    tags: ["Image"],
  },
  {
    id: "file-dsc-raw",
    bucketId: "my-archive",
    kind: "file",
    fileType: "raw",
    name: "DSC_8492_Edited_Final.raw",
    slug: "DSC_8492_Edited_Final.raw",
    path: ["Travel Photos"],
    owner: "Me",
    updatedAt: "2026-04-16T14:05:00.000Z",
    sizeBytes: 65000000,
    tags: ["Photography"],
  },
  {
    id: "file-broll",
    bucketId: "my-archive",
    kind: "file",
    fileType: "video",
    name: "B_Roll_Forest_Sequence_04.mp4",
    slug: "B_Roll_Forest_Sequence_04.mp4",
    path: ["Work Assets"],
    owner: "Me",
    updatedAt: "2026-04-13T12:00:00.000Z",
    sizeBytes: 1200000000,
    tags: ["Video"],
  },
  {
    id: "file-client-brief",
    bucketId: "shared",
    kind: "file",
    fileType: "pdf",
    name: "Client_Brief_V2_Draft.pdf",
    slug: "Client_Brief_V2_Draft.pdf",
    path: [],
    owner: "Sarah Jenkins",
    updatedAt: "2026-04-18T13:10:00.000Z",
    sizeBytes: 4800000,
    tags: ["Shared"],
    shared: true,
  },
  {
    id: "file-tax-summary",
    bucketId: "vault",
    kind: "file",
    fileType: "pdf",
    name: "Tax_Summary_2024.pdf",
    slug: "Tax_Summary_2024.pdf",
    path: [],
    owner: "Me",
    updatedAt: "2026-04-02T11:10:00.000Z",
    sizeBytes: 2400000,
    tags: ["Private", "Finance"],
    vaulted: true,
  },
];

export const collections: CollectionCard[] = [
  {
    id: "collection-work-assets",
    title: "Work Assets",
    objectCount: 24,
    updatedLabel: "2h ago",
    href: buildArchiveHref("my-archive", ["Work Assets"]),
  },
  {
    id: "collection-travel-photos",
    title: "Travel Photos",
    objectCount: 1402,
    updatedLabel: "yesterday",
    shared: true,
    href: buildArchiveHref("my-archive", ["Travel Photos"]),
  },
  {
    id: "collection-financials",
    title: "Financials 2024",
    objectCount: 8,
    updatedLabel: "last week",
    href: buildArchiveHref("my-archive", ["Financials 2024"]),
  },
];

export const transfers: TransferItem[] = [
  {
    id: "transfer-raw",
    fileName: "DSC_8492_Edited_Final.raw",
    totalBytes: 65000000,
    transferredBytes: 42000000,
    tickBytes: 4200000,
    status: "uploading",
    statusLabel: "42 MB of 65 MB • 2 secs left",
    targetLabel: "My Archive",
  },
  {
    id: "transfer-video",
    fileName: "B_Roll_Forest_Sequence_04.mp4",
    totalBytes: 1200000000,
    transferredBytes: 145000000,
    tickBytes: 44000000,
    status: "uploading",
    statusLabel: "145 MB of 1.2 GB • 4 mins left",
    targetLabel: "My Archive",
  },
  {
    id: "transfer-pdf",
    fileName: "Client_Brief_V2_Draft.pdf",
    totalBytes: 4800000,
    transferredBytes: 0,
    tickBytes: 0,
    status: "queued",
    statusLabel: "Waiting for current transfer...",
    targetLabel: "My Archive",
  },
];
