services:
  drive-webui:
    image: ghcr.io/suraj7026/drive-webui:latest
    container_name: surajdrive-frontend
    ports:
      - "4000:4000"
    environment:
      - NEXT_PUBLIC_API_URL=https://drive.sudarshanrajagopalan.one/drive-api
      - API_URL=https://drive.sudarshanrajagopalan.one/drive-api
      - BACKEND_URL=https://drive.sudarshanrajagopalan.one/drive-api
    restart: always
